complete -c nsdiff -l help -d "help"
complete -c nsdiff -l version -d "version"
complete -c nsdiff -l json -d "json"
complete -c nsdiff -l only-differences -d "only differences"
complete -c nsdiff -l explain -d "explain"
complete -c nsdiff -l summary -d "summary"
complete -c nsdiff -l quiet -d "quiet"
complete -c nsdiff -l section -d "section" -r -a "namespaces credentials limits cgroup network mounts environment security all"
complete -c nsdiff -l capture -d "capture"
complete -c nsdiff -l against -d "against"
complete -c nsdiff -l snapshots -d "snapshots"
complete -c nsdiff -l snapshot-info -d "snapshot info"
complete -c nsdiff -l verify-snapshot -d "verify snapshot"
complete -c nsdiff -l snapshot-compat -d "snapshot compat"
complete -c nsdiff -l snapshot-id -d "snapshot id"
complete -c nsdiff -l semantic-id -d "semantic id"
complete -c nsdiff -l snapshot-manifest -d "snapshot manifest"
complete -c nsdiff -l snapshot-schema -d "snapshot schema"
complete -c nsdiff -l export-snapshot-json -d "export snapshot json"
complete -c nsdiff -l convert-snapshot -d "convert snapshot"
complete -c nsdiff -l snapshot-format -d "snapshot format" -r -a "native portable"
